class Configuration:
    CREATE_TILE_INF = """
CREATE TABLE IF NOT EXISTS TILE_INF
(LV INTEGER, TILE_ID TEXT, GEOHASH TEXT, TOP_LEFT_X REAL, TOP_LEFT_Y REAL, BOTTOM_RIGHT_X REAL, BOTTOM_RIGHT_Y REAL,
 CENTER_X REAL, CENTER_Y REAL)""".strip()

    INSERT_TO_TILE_INF = """
INSERT INTO TILE_INF(LV) VALUES(1)""".strip()

    SELECT_TILE_INF = """
SELECT * FROM TILE_INF""".strip()
